version: '3.9'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/PROJECT_NAME
    depends_on:
      - postgres

  ai:
    build:
      context: ../ai
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: PROJECT_NAME
      POSTGRES_USER: PROJECT_NAME
      POSTGRES_PASSWORD: PROJECT_NAME
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
